server:
  port: 9555
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Asd8711341
    url: jdbc:mysql://101.200.216.156:3306/db_bbs?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Hongkong
  application:
    name: bbs-topic
mybatis:
  configuration:
    map-underscore-to-camel-case: true    #将_转为驼峰命名
mapper:
  identity: MYSQL   # 标识列用mysql  配置主键自动增长

logging:  #日志配置
  level:
    com.yc.springcloud812: debug

eureka:
  client:
    service-url:
      defaultZone: http://admin:a@eureka1:7001/eureka
  instance:
    instance-id: bbs-topic_1   #实例名


#监控配置
info:
  app.name: BBS-TOPIC
  company.name: gsn
  build.artifactId: $project.artifactId$
  build.modelVersion: $project.modelVersion$
  build.version: $project.version$
  jdk.version: $java.version$